//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMSOC
    {
        public int ID { get; set; }
        public string TenCachChamSoc { get; set; }
        public string MoTa { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<int> CS_ID { get; set; }
        public string TieuDeSeo { get; set; }
        public string Alias { get; set; }
    
        public virtual DMCHAMSOC DMCHAMSOC { get; set; }
    }
}
