//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CTHD = new HashSet<CTHD>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> PTTTID { get; set; }
        public string Mota { get; set; }
        public Nullable<int> SoLuongDonHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHD { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
