//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public int ID { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public string Gmail { get; set; }
        public Nullable<int> Diem { get; set; }
        public string SDT { get; set; }
    }
}
