//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public int ID { get; set; }
        public string TenKM { get; set; }
        public string MoTa { get; set; }
        public string NoiDung { get; set; }
        public string TieuDeSeo { get; set; }
        public Nullable<int> MDKM_ID { get; set; }
        public string TuKhoa { get; set; }
    
        public virtual DMKM DMKM { get; set; }
    }
}
