//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public string Link { get; set; }
        public string MoTa { get; set; }
        public string TIeuDeSeo { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    }
}
