//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int ID { get; set; }
        public string TenTinTuc { get; set; }
        public string MoTa { get; set; }
        public string NoiDung { get; set; }
        public string TuKhoa { get; set; }
        public int DMTT_ID { get; set; }
        public string TieuDeSeo { get; set; }
        public string Alias { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual DMTT DMTT { get; set; }
    }
}
