//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebCayCanhEntities : DbContext
    {
        public WebCayCanhEntities()
            : base("name=WebCayCanhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHAMSOC> CHAMSOC { get; set; }
        public virtual DbSet<CHINHSACH> CHINHSACH { get; set; }
        public virtual DbSet<CTHD> CTHD { get; set; }
        public virtual DbSet<DMCHAMSOC> DMCHAMSOC { get; set; }
        public virtual DbSet<DMCHINHSACH> DMCHINHSACH { get; set; }
        public virtual DbSet<DMKM> DMKM { get; set; }
        public virtual DbSet<DMSP> DMSP { get; set; }
        public virtual DbSet<DMTT> DMTT { get; set; }
        public virtual DbSet<FOOTER> FOOTER { get; set; }
        public virtual DbSet<GIOITHIEU> GIOITHIEU { get; set; }
        public virtual DbSet<HINHANH> HINHANH { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<HUONGDAN> HUONGDAN { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAI { get; set; }
        public virtual DbSet<LIENHE> LIENHE { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNG { get; set; }
        public virtual DbSet<PHANHOI> PHANHOI { get; set; }
        public virtual DbSet<PTTT> PTTT { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
        public virtual DbSet<Slide> Slide { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TINTUC> TINTUC { get; set; }
    }
}
